name: CI Pipeline
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: |
          cd lambda
          npm install

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: |
          cd lambda
          npm install

      - name: Compress Lambda function
        run: zip -r lambda.zip .
        working-directory: lambda

      - name: Build Docker image
        run: docker build -t serverless-weather-app -f Docker/Dockerfile .

      - name: Run Docker container
        run: docker run -e WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} serverless-weather-app
